### ISSUE TITLE
Save New Entity

### ISSUE THREAD

**Issue by azitter91** [vlucas/Spot#49]
I'm having an issue updating entities with both save() and update() using an empty entity object. It seems that even if I fill it with matching primary key information for an existing row, it will return true, but not update. However, an entity that already exists through get() will update properly.

$ent = $this->mapper->get('\Entity\Foo', 'pk');
$ent->bar = '23';
return $this->mapper->save($ent);
// Returns true, row is updated

$data = array('pk' => 'pk', 'bar' => '23');
return $this->mapper->save(new \Entity\Foo($data));
// Returns true, row remains unchanged

return $this->mapper->insert(new \Entity\Foo($data));
// Returns true, new row added

**Comment by vlucas** [comment]
So let me make sure I have the steps correct, so I can re-produce this:
1. Get existing entity via `get`, update it and save it
2. Save entity via object with existing record's PK does not load it and save it in a single step, and you expect it to
3. Inserting the record works (confused on whether or not you are using the same PK here or not... an actual value would help clear that up

**Comment by azitter91** [comment]
That's correct. Let me try this again with actual information:

```
| class_id  | asset_class | sub_class |
|-----------+-------------+-----------|
| 11        | Commodity   | Metals    |
```

First, updating an existing row through save()

```
// Updates row and returns true
$ent = $this->mapper->get('\Application\Entities\Classes', '11');
$ent->asset_class = 'Money';
$ent->sub_class = 'Nonmetals';
return $this->mapper->save($ent);
```

Second, updating an existing row through save() using an array

```
// Does not update row and returns true
$data = array(
    'class_id' => '11',
    'asset_class' => 'Money',
    'sub_class' => 'Nonmetals'
);
return $this->mapper->save(new \Application\Entities\Classes($data));
```

Third, adding a new row through save() using an array

```
// Does not create row and returns true
$data = array(
    'class_id' => '20',
    'asset_class' => 'Money',
    'sub_class' => 'Nonmetals'
);
return $this->mapper->save(new \Application\Entities\Classes($data));
```

Finally, adding a new row through insert() using an array

```
// Creates a new row and returns the primary key
$data = array(
    'class_id' => '20',
    'asset_class' => 'Money',
    'sub_class' => 'Nonmetals'
);
return $this->mapper->insert(new \Application\Entities\Classes($data));
```

My understanding was that save() would either update the row if it exists, or create a new row if it didn't. I'm working on an application where either is possible, and it would be nice to have one function for both cases, instead of having to first check if the row exists.

**Comment by vlucas** [comment]
Thanks for the more detailed information. In your `\Application\Entities\Classes` entity class, do you have `class_id` set with `'primary' => true` in the `fields` array?

**Comment by azitter91** [comment]
Yes.

```
namespace Application\Entities;

class Classes extends \Spot\Entity
{
    protected static $_datasource = 'classes';

    public static function fields()
    {
        return array(
            'class_id' => array('type' => 'int', 'primary' => true),
            'asset_class' => array('type' => 'string'),
            'sub_class' => array('type' => 'string')
        );
    }

    public static function relations()
    {
        return array(
        );
    }
}
```

**Comment by vlucas** [comment]
I was thinking about this over the weekend and what to do about this. This behavior seems like an `upsert` more than the specific expected behavior of `save`. I think the best way to go about this at least for now is to add a new `upsert` method on the mapper instead of doing this implicitly through `save`. Thoughts @pnomolos?

**Comment by vlucas** [comment]
Re-opened because this needs more work - namely, we need to FETCH the record BEFORE UPDATING it, or any other changes won't be saved for the Entity.

The code should be more like this:

``` php
try {
    $entity = new Entity($data);
    $result = $mapper->insert($entity);
} catch(\Exception $e) {
    $entity = $mapper->first('Entity', array('unique_id_that_fails_insert' => $data['id']));
    if(!$entity) {
        throw $e;
    }
    $entity->data($data);
    $result = $mapper->update($entity);
}
```

This code comes directly from another project of mine where I as trying to use `upsert`. It was working in the sense that it wasn't throwing exceptions if the record already existed, but it wasn't updating any modified data in any of the fields on the Entity, because it doesn't actually select the record to update it first (i.e. it doesn't have a loaded record with primary key). I should have known better and/or tested more thoroughly, so this one's my bad. I'll get it fixed and push out a new release of Spot very soon.
